# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: How Journalism Can Thrive
email: hello@reboot.org
description: > # this means to ignore newlines until "baseurl:"
  Kenya’s “establishment media” is cited as the strongest in the region, if not the continent. While this rosy view is held both abroad, it stands in sharp contrast to the lived experiences of journalists and editors, weighed down by political and commercial interests, corruption, and an antagonistic state.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://strongermediakenya.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: [here]
twitter_username: theReboot
github_username:  theReboot

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - octopress-autoprefixer
sass:
  style: compressed
